export const list = [
  { name: "United States", code: "US" },
  { name: "Japan", code: "JP" },
  { name: "India", code: "IN" },
  { name: "South Korea", code: "KR" },
  { name: "United Kingdom", code: "GB" },
  { name: "Australia", code: "AU" },
  { name: "Belgium", code: "BE" },
  { name: "Brazil", code: "BR" },
  { name: "Canada", code: "CA" },
  { name: "China", code: "CN" },
  { name: "Denmark", code: "DK" },
  { name: "France", code: "FR" },
  { name: "Germany", code: "DE" },
  { name: "Italy", code: "IT" },
  { name: "Ireland", code: "IE" },
  { name: "Mexico", code: "MX" },
  { name: "Netherlands", code: "NL" },
  { name: "New Zealand", code: "NZ" },
  { name: "Philippines", code: "PH" },
  { name: "Portugal", code: "PT" },
  { name: "Serbia", code: "RS" },
  { name: "Spain", code: "ES" },
  { name: "Indonesia", code: "ID" },
];
